# block create/edit/delete anonymously from MLFlow UI
# allow anonymous readonly

worker_processes 1;
pid /home/user/nginx.pid;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;

    upstream mlflow_backend {
        server 127.0.0.1:5000;
    }

    server {
        listen 7860;

        location ~* ^/ajax-api/2.0/mlflow/(experiments|runs)/(create|delete|update) {
            auth_basic "MLflow Admin Access Required";
            auth_basic_user_file /home/user/app/.htpasswd;

            proxy_pass http://mlflow_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # else allowed
        location / {
            proxy_pass http://mlflow_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
